version: '3.8'

services:
  app:
    build: .
    container_name: app-guardiao-pantaneiro
    ports:
      - "8182:8182"
    restart: always
    networks:
      - rede-karate

networks:
  rede-karate:
    external: true